parameters:
    # Common config database
    app.database.common:
        dsn:      'mysql:dbname=%eka.dm.blog.secret.database.schema%;host=%eka.dm.blog.secret.database.host%;charset=UTF8'
        username: '%eka.dm.blog.secret.database.username%'
        password: '%eka.dm.blog.secret.database.password%'
        options:
            !php/const \PDO::MYSQL_ATTR_INIT_COMMAND: "SET NAMES 'UTF8'"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Eureka\Component\Database\ConnectionFactory:
        arguments:
            $configs:
                common: '%app.database.common%'

    Eureka\Component\Orm\:
        resource: '../../vendor/eureka/component-orm/src/*'
        exclude: '../../vendor/eureka/component-orm/src/{Script}'

    Eureka\Component\Validation\:
        resource: '../../vendor/eureka/component-validation/src/*'

    #~ ORM Generator Script (need to be public for Console)
    Eureka\Component\Orm\Script\Generator:
        public: true

    #~ Public factory alias for ORM Generator
    database.factory:
        public: true
        alias: 'Eureka\Component\Database\ConnectionFactory'
