parameters:

    #~ Comment part
    orm.comment.author:    'Eureka Orm Generator'
    orm.comment.copyright: 'Romain Cottard'

    #~ Namespace base config
    orm.base_namespace.entity:     'Eureka\Domain\Page'
    orm.base_namespace.mapper:     'Eureka\Domain\Page'
    orm.base_namespace.repository: 'Eureka\Domain\Page'

    #~ Path base config
    orm.base_path.entity:     '%kernel.directory.root%/src'
    orm.base_path.mapper:     '%kernel.directory.root%/src'
    orm.base_path.repository: '%kernel.directory.root%/src'

    #~ Cache base config
    orm.cache.prefix: 'eka.dm.blog.'

    #~ Validation
    orm.validation.enabled: true
    orm.validation.auto:    true

    orm.configs:
        #~ Core Blog
        page:   '%orm.config.page%'
