<?php

/*
 * Copyright (c) Romain Cottard
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Eureka\Domain\Page\Infrastructure\Mapper\Abstracts;

use Eureka\Component\Orm\AbstractMapper;
use Eureka\Domain\Page\Entity\PageTranslation;

/**
 * Abstract PageTranslation mapper class.
 *
 * /!\ AUTO GENERATED FILE. DO NOT EDIT THIS FILE.
 * You can add your specific code in child class: {{ class.child }}
 *
 * @author Eureka Orm Generator
 */
abstract class AbstractPageTranslationMapper extends AbstractMapper
{
    /**
     * Initialize mapper with proper values for mapped table.
     *
     * @return void
     */
    protected function initialize(): void
    {
        $this->setEntityClass(PageTranslation::class);
        $this->setTable('page_translation');

        $this->setFields([
            'page_id',
            'lang_code',
            'page_translation_content'
        ]);

        $this->setPrimaryKeys([
            'page_id',
            'lang_code'
        ]);

        $this->setNamesMap([
            'page_id' => [
                'get'      => 'getPageId',
                'set'      => 'setPageId',
                'property' => 'pageId',
            ],
            'lang_code' => [
                'get'      => 'getLangCode',
                'set'      => 'setLangCode',
                'property' => 'langCode',
            ],
            'page_translation_content' => [
                'get'      => 'getContent',
                'set'      => 'setContent',
                'property' => 'content',
            ],
        ]);

        $this->setValidatorConfig([
            'page_id' => [
                'type'      => 'integer',
                'options'   => ['min_range' => 0, 'max_range' => 4294967295],
            ],
            'lang_code' => [
                'type'      => 'string',
                'options'   => ['min_length' => 0, 'max_length' => 2],
            ],
            'page_translation_content' => [
                'type'      => 'string',
                'options'   => ['min_length' => 0, 'max_length' => 65535],
            ],
        ]);

        $this->setJoinConfigs([
        ]);
    }
}
