# Services Yaml file
parameters:


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Eureka\Domain\:
        resource: '../src/*'
