# ORM Config file
parameters:

  orm.config.page_translation:
    comment:
      author: '%orm.comment.author%'
      copyright: '%orm.comment.copyright%'

    namespace:
      entity: '%orm.base_namespace.entity%\Entity'
      mapper: '%orm.base_namespace.mapper%\Infrastructure\Mapper'
      repository: '%orm.base_namespace.repository%\Repository'

    path:
      entity: '%orm.base_path.entity%/Entity'
      mapper: '%orm.base_path.mapper%/Infrastructure/Mapper'
      repository: '%orm.base_path.repository%/Repository'

    cache:
      prefix: '%orm.cache.prefix%page_translation'

    database:
      table: 'page_translation'
      prefix: 'page_translation'

    class:
      classname: 'PageTranslation'

    joins: [ ]


    #~ Validation input in entities
    validation:
      enabled: '%orm.validation.enabled%'
      auto: '%orm.validation.auto%'
      extended_validation: ~
